### ISSUE TITLE
Any plans for a docker image of this?

### ISSUE THREAD

**Issue by vswraith** [MatthK/Selfoss-Webfront#2]

**Comment by MatthK** [comment]
I have had a look and gave it a try. As I don't have any experience with creating docker images, it didn't work out.

For the time being I have abandoned that idea, as I want to make a few more improvements on the solution itself instead of investing time on the docker image. I'd be happy to add that with getting some help with that. Some specific issues I have:

- How to get two virtual hosts/websites in one docker?
- How to get a cron job running in the docker image?
- How to get the mysql database in the same docker?

I also tried with docker-compose, but face at least the first two questions there too. And when I tried the docker-compose, how can I link it to my existing MySQL docker?

**Comment by guim31** [comment]
I'm sad I can't help you ! Maybe you should ask Linuxserver to see if they could create a docker container !

**Comment by dseller** [comment]
> How to get two virtual hosts/websites in one docker?

You would use a webserver like Nginx to handle that for you. Just make sure you configure it right and you can expose two ports instead of one. That would be a possible solution, and I think the easiest one to achieve.

> How to get a cron job running in the docker image?

That is tricky. In my experience, cron and docker containers do not work together very well. There are some tutorials about this though. Make sure you use a proper solution like `supervisord` when running multiple processes in one container. 

> How to get the mysql database in the same docker?

Typically, you don't. The database usually runs in a different container (or bare metal, depends on the environment). You would usually provide a few environment variables to the docker container to tell the application where the database server is (e.g. `DB_HOST`, `DB_USER`, `DB_PASS`, etc.)

Hope it helps.

**Comment by potts99** [comment]
Is this still an issue? I have worked on docker files for my OSS project and managed to get it working

**Comment by MatthK** [comment]
Yes, it is. I haven't tried working on that anymore. If you can help, that would certainly be a welcome addition.

**Comment by potts99** [comment]
I'll take a look tonight and create a docker file for you :)

**Comment by vswraith** [comment]
@potts99 were you able to create the docker file? Can you please help share?

**Comment by MatthK** [comment]
Here you go: [https://github.com/MatthK/swfd](https://github.com/MatthK/swfd)
